packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  valtio@*:
    dependencies:
      "@babel/helper-module-imports": "*"
      "@babel/types": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.2.1.cjs
