packageExtensions:
  styled-components@*:
    dependencies:
      react-is: '*'
  valtio@*:
    dependencies:
      '@babel/helper-module-imports': '*'
      '@babel/types': '*'

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.2.1.cjs
